name: Tests

on:
  push:

jobs:

  phpunit_11:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2', '8.3']
    name: Run PHPUnit v11.0.9 by PHP ${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Composer
        uses: php-actions/composer@v6

      - name: PHPUnit
        uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          version: "11.0.9"
          php_version: ${{ matrix.php }}

  phpunit_10:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.1']
    name: Run PHPUnit v10 by PHP ${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Composer
        uses: php-actions/composer@v6

      - name: PHPUnit
        uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          version: "10"
          php_version: ${{ matrix.php }}

  phpunit_9:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4', '8.0']
    name: Run PHPUnit v9 by PHP ${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Composer
        uses: php-actions/composer@v6

      - name: PHPUnit
        uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          version: "9"
          php_version: ${{ matrix.php }}
