name: Run tests

on:
  push:

jobs:
  phpunit:
    name: Run PHPUnit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          version: "11.1.1"
          php_version: "8.2"
